apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: floatingips.network.tmaxanc.com
spec:
  group: network.tmaxanc.com
  names:
    kind: FloatingIP
    listKind: FloatingIPList
    plural: floatingips
    singular: floatingip
    shortNames:
    - fip
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              externalIP:
                description: Desired external IP
                type: string
              podName:
                type: string
            required:
            - externalIP
            - podName
          status:
            type: object
            properties:
              allocatedIP:
                description: Currently allocated external IP
                type: string
    additionalPrinterColumns:
    - jsonPath: .status.allocatedIP
      name: External-IP
      type: string
    subresources:
      status: {}
