apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: publicippools.network.tmaxanc.com
spec:
  group: network.tmaxanc.com
  names:
    kind: PublicIPPool
    listKind: PublicIPPoolList
    plural: publicippools
    singular: publicippool
  scope: Cluster
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              publicAddresses:
                items:
                  type: string
                type: array
            required:
            - publicAddresses
            type: object
          status:
            properties:
              observedGeneration:
                type: integer
                format: int64
            type: object
        type: object
    subresources:
      status: {}