apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: stonelb
  name: stonelb-service-account
  namespace: hypersdn-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: hypersdn-system
  name: stonelb-clusterrole
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services/status"]
  verbs: ["update"]
- apiGroups: ["network.tmaxanc.com"]
  resources: ["publicippools", "floatingips"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["network.tmaxanc.com"]
  resources: ["floatingips/status", "publicippools/status"]
  verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:  
  labels:
    app: stonelb
  name: stonelb-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: stonelb-service-account
  namespace: hypersdn-system
roleRef:
  kind: ClusterRole
  name: stonelb-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stonelb
  namespace: hypersdn-system
  labels:
    app: stonelb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stonelb
  template:
    metadata:
      labels:
        app: stonelb
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: Exists
      containers:
        - name: stonelb
          image: tmaxcloudck/stonelb:v0.1.0-dev
      serviceAccountName: stonelb-service-account
